### PR TITLE
Django 2.2

### PR DESCRIPTION
**Pull request by richardbarran**
I'm opening a new branch for testing compatibility with Django 2.2 - although I have not tested it yet, this PR can be used to track progress.

### CODE REVIEW

**Comment by richardbarran** [comment]
Well Django-fiber seems to work well for me in Django 2.2 - @ramonakira, could you test this branch and check that it also works for you?

**Comment by ramonakira** [comment]
Hi @richardbarran, Looks good! I found another small issue with regard to the display of images in the ImageAdmin list. It probably already existed in Django 2.1 but fixed it here now.

**Comment by ramonakira** [comment]
Hi @richardbarran, seems this can be merged. Can you create a new release?

**Comment by richardbarran** [comment]
I've merged this branch and released Django-fiber 1.6 - now works with Django 2.2.
Many thanks @ramonakira.

**Pull request merged**
