### PR TITLE
Django 3.0

### PR DESCRIPTION
**Pull request by jaap3**
This add Django 3.0 support and drops Python 2 and Django < 2.2 support.

See also #271

### CODE REVIEW

**Comment by richardbarran** [comment]
Hi @jaap3  - what is the current status on this PR? Are you still working on it, or are you busy elsewhere and you cannot continue at present on Django 3.0 stuff?

**Comment by jaap3** [comment]
I was waiting for all dependencies to become Django 3.0 compatible (and enjoying the christmas break). Everything seems good to go now.

**Comment by richardbarran** [comment]
My apologies - I missed the updates on this thread.
I've deployed this branch to a production website that I run, no issues to report. I'm happy to merge.

**Comment by richardbarran** [comment]
@jaap3 I've merged in this PR - I'll make a new release of Django-fiber in the next few days.

**Comment by jaap3** [comment]
Thank you, no worries about the delay :)

**Comment by richardbarran** [comment]
I've just released django-fiber 1.7 with your branch.

**Pull request merged**
