### PR TITLE
Set Content-Lenght header after modifying content

### PR DESCRIPTION
**Pull request by jaap3**

### CODE REVIEW

**Comment by richardbarran** [comment]
I haven't tested it, but the code looks good to me. Just one thing: could you update the README please?

**Comment by jaap3** [comment]
What exactly would you like to see updated in the README?

**Comment by richardbarran** [comment]
My apologies! I was thinking of updating the CHANGELOG with a short description of your change, but typed README instead.

**Comment by jaap3** [comment]
@richardbarran Sorry for the delay, but finally I got around to updating the `CHANGELOG` (and tweaked the code a bit as well). For reference, this https://github.com/django/django/blob/2.2.7/django/middleware/common.py#L111 is the code that would cause the `Content-Length` header to be set in the first place.

**Comment by richardbarran** [comment]
Looks good to me!

**Pull request merged**
