### PR TITLE
Add migration to handle mptt schema change

### PR DESCRIPTION
**Pull request by jaap3**
This should fix issue #278

### CODE REVIEW

**Comment by richardbarran** [comment]
Looks good - I'll add a note to the CHANGELOG explaining why the migration is required.

**Comment by jaap3** [comment]
Thanks Richard!

**Comment by jaap3** [comment]
@richardbarran I just installed fiber 1.8 and for some reason this migration is not included in the package. I have yet to figure out why it is missing.

**Comment by jaap3** [comment]
I figured it out, the new migration was missing the .py extension. Whoops! PR #281 should fix it.

**Pull request merged**
